/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FeedingsRouteImport } from './routes/feedings'
import { Route as LitterRouteImport } from './routes/litter'
import { Route as PoopsRouteImport } from './routes/poops'
import { Route as WeightsRouteImport } from './routes/weights'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedingsRoute = FeedingsRouteImport.update({
  id: '/feedings',
  path: '/feedings',
  getParentRoute: () => rootRouteImport,
} as any)
const LitterRoute = LitterRouteImport.update({
  id: '/litter',
  path: '/litter',
  getParentRoute: () => rootRouteImport,
} as any)
const PoopsRoute = PoopsRouteImport.update({
  id: '/poops',
  path: '/poops',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightsRoute = WeightsRouteImport.update({
  id: '/weights',
  path: '/weights',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feedings': typeof FeedingsRoute
  '/litter': typeof LitterRoute
  '/poops': typeof PoopsRoute
  '/weights': typeof WeightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feedings': typeof FeedingsRoute
  '/litter': typeof LitterRoute
  '/poops': typeof PoopsRoute
  '/weights': typeof WeightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feedings': typeof FeedingsRoute
  '/litter': typeof LitterRoute
  '/poops': typeof PoopsRoute
  '/weights': typeof WeightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/feedings' | '/litter' | '/poops' | '/weights'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/feedings' | '/litter' | '/poops' | '/weights'
  id:
    '__root__' | '/' | '/auth' | '/feedings' | '/litter' | '/poops' | '/weights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FeedingsRoute: typeof FeedingsRoute
  LitterRoute: typeof LitterRoute
  PoopsRoute: typeof PoopsRoute
  WeightsRoute: typeof WeightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedings': {
      id: '/feedings'
      path: '/feedings'
      fullPath: '/feedings'
      preLoaderRoute: typeof FeedingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/litter': {
      id: '/litter'
      path: '/litter'
      fullPath: '/litter'
      preLoaderRoute: typeof LitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poops': {
      id: '/poops'
      path: '/poops'
      fullPath: '/poops'
      preLoaderRoute: typeof PoopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weights': {
      id: '/weights'
      path: '/weights'
      fullPath: '/weights'
      preLoaderRoute: typeof WeightsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FeedingsRoute: FeedingsRoute,
  LitterRoute: LitterRoute,
  PoopsRoute: PoopsRoute,
  WeightsRoute: WeightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
